load python 3.12.0.
remove Scientific Linux 7 libraries.
load Scientific Linux 7 libraries.
load tcltk 8.5.13 (GCC) library and binaries.
remove Scientific Linux 7 libraries.
load Scientific Linux 7 libraries.
Traceback (most recent call last):
  File "/lustre/nobackup/WUR/ESG/zhou111/Code/Data_Processing/Result_Analysis/1_Yp_Cult_SD/1_Get_Yp_SD_tsum.py", line 18, in <module>
    df = pd.read_csv(model_result)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/legacyapps/python/3.12.0/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/legacyapps/python/3.12.0/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/legacyapps/python/3.12.0/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/legacyapps/python/3.12.0/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/shared/legacyapps/python/3.12.0/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/nobackup/WUR/ESG/zhou111/WOFOST-Nutrient/CaseStudy/Rhine/Output/Output_Yp/maize_Yp_1985-2014.csv'
